/*
 * This source file was generated by the Gradle 'init' task
 */
package fold;

import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import com.google.gson.Gson;
import com.google.gson.JsonArray;

import kotlin.Pair;

import com.google.gson.*;



public class App {
    OkHttpClient client = new OkHttpClient();
    public String getGreeting() {
        return "Hello World!";
    }

    public String getText(String url,String subUrl) throws IOException{
        Request request = new Request.Builder().url(url+"/"+subUrl).header("X-TBA-Auth-Key",Constants.apiKey).build();

        try(Response response = client.newCall(request).execute()){
            return response.body().string();
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String text = "";
        try {
           text =  (new App().getText("https://www.thebluealliance.com/api/v3","event/"+Constants.eventKey+"/teams/keys"));
        } catch (Exception e) {
            System.out.print("Oopsies");
        }

        String[] listTeams = teamsList(text);
        
            // System.out.println((listTeams[listTeams.length-2]));

            // System.out.println(getNextMatch(listTeams[listTeams.length-2]));
        //TreeMap<Integer,String> map = new TreeMap<Integer,String>();
        List<Pair<String,Integer>> list = new ArrayList<Pair<String,Integer>>();
        for(String s:listTeams){
            
            System.out.println((s));

            String[] matchesList = getNextMatch(s);
            
            List<String> matchArr = Arrays.asList(matchesList).stream().filter((match)->match.contains("qm")).collect(Collectors.toList());
            System.out.println(getDifference(matchArr));
            list.add(new Pair<String,Integer>(s,getDifference(matchArr)));
        }
        list.sort((team, nextTeam)-> nextTeam.getSecond()-team.getSecond());
        for(Pair<String, Integer> pairs:list){
            System.out.println("Team: "+pairs.getFirst()+" Match Differece: "+pairs.getSecond());
        }
        // map.values().forEach((teamName)->System.out.println(teamName));
        // map.keySet().forEach((teamName)->System.out.println(teamName));


       // System.out.println(text);
    }
    public static String[] teamsList(String teamKeys){
        return new Gson().fromJson(teamKeys, String[].class);
        // teamKeys = teamKeys.substring(1,teamKeys.length()-2);
        // String[] teamList = teamKeys.split(",");
        // for(int i=0;i<teamList.length;i++){
        //     teamList[i] = teamList[i].substring(4,teamList[i].length()-2);
        // }
        // return teamList;
        }
    public static String[] getNextMatch(String teamCode){
        String text = "";
        try{
         text = (new App().getText("https://www.thebluealliance.com/api/v3","team/"+teamCode+"/event/"+Constants.eventKey+"/matches/keys"));
        }catch(Exception e){
            System.out.print("Oopsies");
        }
        return new Gson().fromJson(text, String[].class);//text;//new Gson().fromJson(text,String[].class);
        
    }
    public static int getDifference(List<String> matchArray){
        int difference = Integer.MAX_VALUE;
        for(String match:matchArray){
            int matchNumber = Integer.parseInt(match.split("qm")[1]);
            if(matchNumber-Constants.currentQualMatch>0&&matchNumber-Constants.currentQualMatch<difference){
                difference = matchNumber-Constants.currentQualMatch;
            }
        }
        return difference;
    }
}
